services:
  # VK Connector service
  vk-connector:
    build:
      context: .
      dockerfile: apps/vk-connector/Dockerfile
    container_name: vk-connector
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped