services:
  # VK Connector service
  vk-connector:
    build:
      context: .
      dockerfile: apps/vk-connector/Dockerfile
    container_name: vk-connector
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vk-connector.rule=Host(`mail.zaruba-ds.ru`)"
      - "traefik.http.routers.vk-connector.entrypoints=websecure"
      - "traefik.http.routers.vk-connector.tls=true"
      - "traefik.http.services.vk-connector.loadbalancer.server.port=3000"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true